version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # NPM_COMMAND: "start"
      NPM_COMMAND: "start.dev"
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
